"use client";

import React, { useState, useEffect } from "react";
import DashboardLayout from "@/components/DashboardLayout";
import {
  Zap,
  DollarSign,
  TrendingUp,
  Award,
  Users,
  Target,
  Sparkles,
  Play,
  Share2,
  MousePointer,
  Eye,
} from "lucide-react";
import {
  ResponsiveContainer,
  AreaChart,
  Area,
  XAxis,
  YAxis,
  CartesianGrid,
  Tooltip,
} from "recharts";

// Real-time active campaign historical records
const activeCampaignsHistory = [
  { date: "May 1", impressions: 2.1, engagements: 0.25, clicks: 45 },
  { date: "May 7", impressions: 3.4, engagements: 0.38, clicks: 68 },
  { date: "May 14", impressions: 5.8, engagements: 0.61, clicks: 110 },
  { date: "May 21", impressions: 8.2, engagements: 0.89, clicks: 175 },
  { date: "May 28", impressions: 10.5, engagements: 1.12, clicks: 215 },
  { date: "Jun 6", impressions: 12.4, engagements: 1.30, clicks: 245 },
];

export default function CampaignSuccessPrediction() {
  const [mounted, setMounted] = useState(false);
  const [budget, setBudget] = useState(25000);
  const [conversionRate, setConversionRate] = useState(2.4); // in %

  // Simulated metrics
  const [successProb, setScore] = useState(87);
  const [revMin, setRevMin] = useState(125000);
  const [revMax, setRevMax] = useState(245000);

  useEffect(() => {
    setMounted(true);
  }, []);

  // Update mock calculations based on inputs
  useEffect(() => {
    const computedScore = Math.min(99, Math.floor(65 + (conversionRate * 8) + (budget * 0.0001)));
    const baseRev = budget * (conversionRate / 100) * 20;
    setScore(computedScore);
    setRevMin(Math.floor(baseRev * 0.8));
    setRevMax(Math.floor(baseRev * 1.5));
  }, [budget, conversionRate]);

  return (
    <DashboardLayout>
      <div className="space-y-6 animate-scale-up">
        {/* Header Title */}
        <div>
          <h1 className="text-2xl font-bold tracking-tight text-white">Campaign Success & ROI Predictor</h1>
          <p className="text-xs text-slate-400 mt-0.5">
            Simulate marketing ROI yields and track active influencer campaigns under a unified monitoring dashboard.
          </p>
        </div>

        {/* Row 1: Interactive Campaign Success Predictor */}
        <div className="grid lg:grid-cols-12 gap-6">
          {/* Inputs Simulator Config */}
          <div className="lg:col-span-5 p-6 rounded-3xl glass-panel space-y-6 flex flex-col justify-between">
            <div className="space-y-6">
              <h3 className="text-sm font-bold text-white uppercase tracking-wider flex items-center gap-1.5">
                <Sparkles className="w-4 h-4 text-primary-purple" />
                Scenario Simulation Inputs
              </h3>

              {/* Budget slider */}
              <div className="space-y-1.5">
                <div className="flex justify-between text-xs font-semibold">
                  <span>Campaign Budget</span>
                  <span className="text-primary-purple font-black">
                    ${budget.toLocaleString()}
                  </span>
                </div>
                <input
                  type="range"
                  min="5000"
                  max="150000"
                  step="2500"
                  value={budget}
                  onChange={(e) => setBudget(Number(e.target.value))}
                  className="w-full accent-primary-purple bg-slate-900 h-1"
                />
              </div>

              {/* Conversion rate estimation */}
              <div className="space-y-1.5">
                <div className="flex justify-between text-xs font-semibold">
                  <span>Assumed Conversion Rate</span>
                  <span className="text-secondary-cyan font-bold">{conversionRate}%</span>
                </div>
                <input
                  type="range"
                  min="0.5"
                  max="8.0"
                  step="0.1"
                  value={conversionRate}
                  onChange={(e) => setConversionRate(Number(e.target.value))}
                  className="w-full accent-secondary-cyan bg-slate-900 h-1"
                />
              </div>
            </div>

            <div className="p-4 rounded-xl bg-slate-950/40 border border-slate-800/40 text-[9px] text-slate-500 font-semibold leading-normal">
              📊 <strong>Predictive Model:</strong> Success percentage is generated by querying creator similarity matrices, audience overlap indexes, and sector benchmarks.
            </div>
          </div>

          {/* Predictor Dashboard Outputs */}
          <div className="lg:col-span-7 p-6 rounded-3xl glass-panel space-y-6">
            <div className="grid sm:grid-cols-2 gap-6">
              {/* Score Indicator */}
              <div className="space-y-2">
                <span className="text-[10px] uppercase font-bold text-slate-500 block">
                  Success Probability
                </span>
                <div className="flex items-baseline gap-2">
                  <span className="text-4xl font-black text-secondary-green">{successProb}%</span>
                  <span className="text-xs text-secondary-green font-semibold">High Chance</span>
                </div>
                <div className="h-2 rounded-full bg-slate-900 overflow-hidden">
                  <div
                    className="h-full bg-secondary-green rounded-full transition-all duration-500"
                    style={{ width: `${successProb}%` }}
                  />
                </div>
              </div>

              {/* Expected Revenue Range */}
              <div className="space-y-2">
                <span className="text-[10px] uppercase font-bold text-slate-500 block">
                  Expected Revenue Potential
                </span>
                <div className="text-2xl font-black text-white">
                  {`$${revMin.toLocaleString()} - $${revMax.toLocaleString()}`}
                </div>
                <span className="text-[10px] text-slate-400 font-medium block">
                  {`Estimated ROI: ${((revMin / budget) * 100).toFixed(0)}% - ${((revMax / budget) * 100).toFixed(0)}%`}
                </span>
              </div>
            </div>

            {/* Success Factors Dimension Lists */}
            <div className="space-y-3 pt-6 border-t border-slate-800/40">
              <span className="text-[10px] font-bold text-slate-500 uppercase tracking-widest block mb-2">
                Success Dimension Weights
              </span>
              {[
                { name: "Audience Match", val: "92%", color: "bg-primary-purple" },
                { name: "Content Relevance", val: "89%", color: "bg-secondary-cyan" },
                { name: "Engagement Quality", val: "85%", color: "bg-secondary-green" },
                { name: "Brand Alignment", val: "84%", color: "bg-accent-gold" },
                { name: "Growth Potential", val: "90%", color: "bg-primary-violet" },
              ].map((factor, idx) => (
                <div key={idx} className="flex items-center justify-between text-xs">
                  <span className="font-semibold text-slate-300 w-36 truncate">{factor.name}</span>
                  <div className="flex-1 mx-4 h-1.5 rounded-full bg-slate-900 overflow-hidden">
                    <div className={`h-full ${factor.color}`} style={{ width: factor.val }} />
                  </div>
                  <span className="font-bold text-white text-[10px]">{factor.val}</span>
                </div>
              ))}
            </div>
          </div>
        </div>

        {/* Row 2: Real-time Campaign Monitoring Dashboard */}
        <div className="space-y-6">
          <div className="flex items-center justify-between">
            <h2 className="text-sm font-bold text-white uppercase tracking-wider">
              Real-time Active Campaigns Monitor
            </h2>
            <span className="px-2 py-0.5 rounded bg-secondary-green/20 text-[9px] text-secondary-green font-bold uppercase">
              Live Updates Sync
            </span>
          </div>

          {/* Quick Metrics Cards */}
          <div className="grid grid-cols-2 sm:grid-cols-4 gap-6">
            <div className="p-4 rounded-2xl glass-panel text-center">
              <span className="text-[10px] text-slate-500 uppercase font-bold">Active Partnerships</span>
              <span className="text-xl font-black text-white mt-1 block">24</span>
              <span className="text-[9px] text-secondary-green font-semibold mt-0.5 block">Online Sync</span>
            </div>
            <div className="p-4 rounded-2xl glass-panel text-center">
              <span className="text-[10px] text-slate-500 uppercase font-bold">Total Impressions</span>
              <span className="text-xl font-black text-white mt-1 block">12.4M</span>
              <span className="text-[9px] text-secondary-green font-semibold mt-0.5 block">+18.5% Week</span>
            </div>
            <div className="p-4 rounded-2xl glass-panel text-center">
              <span className="text-[10px] text-slate-500 uppercase font-bold">Total Engagements</span>
              <span className="text-xl font-black text-white mt-1 block">1.3M</span>
              <span className="text-[9px] text-secondary-green font-semibold mt-0.5 block">+22.1% Week</span>
            </div>
            <div className="p-4 rounded-2xl glass-panel text-center">
              <span className="text-[10px] text-slate-500 uppercase font-bold">Total Link Clicks</span>
              <span className="text-xl font-black text-white mt-1 block">245K</span>
              <span className="text-[9px] text-secondary-green font-semibold mt-0.5 block">+15.3% Week</span>
            </div>
          </div>

          {/* Area Chart mapping traffic over time */}
          <div className="p-6 rounded-3xl glass-panel space-y-4">
            <div className="flex justify-between items-center text-xs">
              <span className="font-bold text-white uppercase tracking-wider">Campaign Metrics Distribution</span>
              <div className="flex gap-4 font-semibold text-[10px] text-slate-400">
                <span className="flex items-center gap-1"><span className="w-2.5 h-1.5 bg-primary-purple/40 rounded" /> Impressions (M)</span>
                <span className="flex items-center gap-1"><span className="w-2.5 h-1.5 bg-secondary-cyan/40 rounded" /> Engagements (M)</span>
              </div>
            </div>

            <div className="w-full h-64">
              {mounted && (
                <ResponsiveContainer width="100%" height="100%">
                  <AreaChart data={activeCampaignsHistory} margin={{ left: -20, top: 10 }}>
                    <defs>
                      <linearGradient id="impColor" x1="0" y1="0" x2="0" y2="1">
                        <stop offset="5%" stopColor="#7B61FF" stopOpacity={0.25} />
                        <stop offset="95%" stopColor="#7B61FF" stopOpacity={0} />
                      </linearGradient>
                      <linearGradient id="engColor" x1="0" y1="0" x2="0" y2="1">
                        <stop offset="5%" stopColor="#00D4FF" stopOpacity={0.25} />
                        <stop offset="95%" stopColor="#00D4FF" stopOpacity={0} />
                      </linearGradient>
                    </defs>
                    <CartesianGrid strokeDasharray="3 3" stroke="#161b30" />
                    <XAxis dataKey="date" stroke="#475569" fontSize={9} />
                    <YAxis stroke="#475569" fontSize={9} />
                    <Tooltip />
                    <Area
                      type="monotone"
                      dataKey="impressions"
                      stroke="#7B61FF"
                      strokeWidth={2.5}
                      fillOpacity={1}
                      fill="url(#impColor)"
                    />
                    <Area
                      type="monotone"
                      dataKey="engagements"
                      stroke="#00D4FF"
                      strokeWidth={2}
                      fillOpacity={1}
                      fill="url(#engColor)"
                    />
                  </AreaChart>
                </ResponsiveContainer>
              )}
            </div>
          </div>
        </div>
      </div>
    </DashboardLayout>
  );
}
